### ISSUE TITLE
Review: Getting started with Camunda Cloud / Phase 2

### ISSUE THREAD

**Issue by urbanisierung** [camunda-cloud/camunda-cloud-documentation#100]
relates #72 

Phase 2: new user experience

- As soon as the new user experience is implemented, the Getting started Guide will be updated accordingly.
- At the end the user should be made aware of the source code of the Getting Started Guide: Idea: own GitHub repo with the source code (Java and NodeJS)
- Bonus: "Setting up your first Development Project" according to the Getting Started Guide (with different programming languages)

**Comment by akeller** [comment]
Covered with 1.0 release! 🥳
