### ISSUE TITLE
Document how to operate a Zeebe standalone gateway

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/camunda-cloud-documentation#105]
**Description**

There is no official documentation on how to configure a Zeebe gateway. There is a documented configuration file, but I would like to see good user documentation how to configure your gateway, how it can be deployed to Kubernetes, how many replicas you should have, how the update process works with it, etc.

When starting this, we should consider splitting it into multiple issues.

**Comment by menski** [comment]
replaced by #381
