### ISSUE TITLE
Fix metadata

### ISSUE THREAD

**Issue by akeller** [camunda-cloud/camunda-cloud-documentation#107]
Remove filler/boilerplate and put relevant metadata on pages.

Priority - index.js

**Comment by akeller** [comment]
@menski can you help me understand who would be the best person to look into this?

**Comment by menski** [comment]
@akeller with "look into this" you mean fixing the things you mentioned or being a SEO expert?

**Comment by akeller** [comment]
Just the changes I outlined above is ok for now. I have a separate issue for Google Analytics that will help us more with SEO and if we need to engage with an actual SEO expert at that time, I'll create a new issue. Thanks @menski!

**Comment by akeller** [comment]
Added site description metadata in #182
