### ISSUE TITLE
Bug: Search results page doesn't populate

### ISSUE THREAD

**Issue by akeller** [camunda-cloud/camunda-cloud-documentation#138]
Steps to reproduce:
* Use the search bar to search for a particular term (with results)
* Scroll down to click link "See all X results"
* Page loads saying no results were found

https://user-images.githubusercontent.com/1051363/104070254-186e6b80-51cc-11eb-8e98-8c77534eac73.mov

**Comment by akeller** [comment]
This works now! 

![image](https://user-images.githubusercontent.com/1051363/125345095-b8dd4e00-e31d-11eb-9156-7078bbb30a9c.png)

**Comment by critesjosh** [comment]
what was the solution for this? I am facing the same issue.

**Comment by akeller** [comment]
We updated our Algolia doc-search config per their recommendations. We were running very outdated config, but I'm not sure how often they update it so it may continue to be a problem.
