### ISSUE TITLE
Integrate Google Analytics

### ISSUE THREAD

**Issue by urbanisierung** [camunda-cloud/camunda-cloud-documentation#159]
use plugin: https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics/

**Comment by akeller** [comment]
Waiting on marketing.

**Comment by akeller** [comment]
This is still held up with marketing as they look for a tool to handle GTM with GDPR compliance.

**Comment by akeller** [comment]
The marketing team has provided me information for integrating with Osano and Google Analytics through GTAG. They've provided instructions that I've added to the Cloud Docs Slack channel. We will not be able to use the Docusaurus Plugin. Please continue this discussion internally if you have questions.

**Comment by akeller** [comment]
Please see #229
