### ISSUE TITLE
Add sitemap

### ISSUE THREAD

**Issue by akeller** [camunda-cloud/camunda-cloud-documentation#162]
We need a sitemap for good SEO. 

While there is a [plugin](https://v2.docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap/) it looks like we can configure this through `@docusaurus/preset-classic`.

**Comment by akeller** [comment]
@urbanisierung can you take a look at this? I'm unsure if we need the plugin or can we just modify the existing configuration. This should greatly improve our SEO since it doesn't look like we have an existing sitemap today.

**Comment by urbanisierung** [comment]
@akeller I've enabled the sitemap in this PR: https://github.com/camunda-cloud/camunda-cloud-documentation/pull/189

Can you please review it? It is already part of the preset theme so it just needs to be enabled.
