### ISSUE TITLE
Improve/Extend Cloud Modeler - Model your first diagram content

### ISSUE THREAD

**Issue by menski** [camunda-cloud/camunda-cloud-documentation#163]
The current content is sparse and seem to stop arbitrary with an incomplete diagram, i.e. the service task type is not defined. 

https://docs.camunda.io/docs/product-manuals/modeler/cloud-modeler/model-your-first-diagram

The guide should give users a useful first model at the end. It could be aligned with the corresponding desktop modeler page https://docs.camunda.io/docs/product-manuals/modeler/zeebe-modeler/model-your-first-diagram from a content perspective or even extended to something similar to the getting started guide in Zeebe https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/getting-started/create-a-workflow.

**Comment by akeller** [comment]
Let's call this done with all the work done for C8 launch and look for other angles to improve modeler docs.
