### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by menski** [camunda-cloud/camunda-cloud-documentation#169]
I don't know if we want to do this but maybe it would be good to add a license to the documentation. Camunda BPM docs are using Creative Commons Public License the https://github.com/camunda/camunda-docs-manual/blob/master/LICENSE.txt

**Comment by akeller** [comment]
Did the Zeebe docs have a separate license? I see they were contained within the Zeebe project repo.

**Comment by menski** [comment]
I don't think we had a specific license for the docs to be honest. Based on this list https://github.com/zeebe-io/zeebe#license I would assume they where published under the Zeebe Community License, which doesn't need to be as they are not source code.

**Comment by akeller** [comment]
Let's add this into 0.27, ahead of the community announcement. I'll add this to my change branch.

**Comment by akeller** [comment]
Merged via #182
