### ISSUE TITLE
Document Zeebe security policy

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/camunda-cloud-documentation#197]
**Description**

Customers and users will eventually want to know how security is handled for Zeebe (and later other Camunda Cloud products), namely:

1. Which versions are supported for security updates?
2. How are vulnerabilities detected by Camunda?
3. What's the management process?
4. How should they report vulnerabilities?

CamBPM already has a good page for this we could use for inspiration: https://docs.camunda.org/security/

Once this is done, please add a `SECURITY.md` file to camunda-cloud/zeebe which links to the page.

I had started a small draft, but since we have no good reporting tool yet, I'm leaving it here as is:

```md
# Security Policy

This document describes how vulnerabilities are managed, reported, and fixed in Zeebe.
It applies strictly to this project - camunda-cloud/zeebe - and no other related projects or community extensions.

## Supported Versions

Unless mentioned otherwise, we will always patch vulnerabilities on the latest two release branches. 
Release branches are all those prefixed with `stable/`, e.g. `stable/0.25`, `stable/1.0`, `stable/1.1`, etc.
The last two minor release branches are essentially the ones with the highest [semantic version](https://semver.org/).

Once a patch is merged on a release branch, we will then publish and announce a new patch release for this branch.

## Reporting a Vulnerability

Please report security vulnerabilities to [zeebe@camunda.com](mailto:zeebe@camunda.com)You can report security vulnerabilities by emailing 
Please clearly outline the vulnerability and how we can confirm it.
```

**Comment by akeller** [comment]
Hi @npepinpe, I wanted to bring a couple of things to your attention. 

I've proposed the creation of camunda.com/security to move our security policy and reporting a vulnerability for all products to a single page. @menski and @felix-mueller are aware this requires a defined process and tooling for Camunda Cloud. 

Please have a look at #210. I have a very slim Security Notices page.

I want to update the information on the Contact page (linked in the footer) to include information about bugs, security, feedback and support. I will cover some of what you mentioned here. Could you please review #203 and #210 to see if I am missing anything?

**Comment by npepinpe** [comment]
It looks fine, but I think it will be easy to miss, and it's not a substitute for something like https://docs.camunda.org/security/, but I guess you know that already since you've proposed a more global approach.

I'm fine with closing this for now and redirecting people to cloud-security@camunda.com. I do have question though - who will manage that email account?

**Comment by akeller** [comment]
Thanks! I agree, we want to make sure this isn't easy to miss. Please keep me honest with this as we continue to pull this information together. If it looks like I'm burying it, please raise that 🙂 

We have an email thread internally to handle the process, including whether we will continue with that email. Sounds like Schuppi's Console team and SRE monitor that email.

**Comment by akeller** [comment]
I have updated the Notices page to link to camunda.com/security with the process for reporting vulnerabilities. Please see #210 https://github.com/camunda-cloud/camunda-cloud-documentation/pull/210/commits/a9683645ad9fb219d7f21ef0ec95358238b6c030
