### ISSUE TITLE
Java client: Example code does not compile

### ISSUE THREAD

**Issue by nevries** [camunda-cloud/camunda-cloud-documentation#230]
In https://github.com/camunda-cloud/camunda-cloud-documentation/blob/master/docs/product-manuals/clients/java-client/get-started.md#work-on-a-job the example code does not compile with 0.26.3. The problematic part is
`try(final JobWorker jobWorker = client.newWorker())`
since newWorker() returns a builder.

**Comment by akeller** [comment]
@menski is this still on your to do list? I'm not sure how relevant it is to get this working on 0.26.

**Comment by akeller** [comment]
Can you check if there are issue with other version as well? @menski

**Comment by berndruecker** [comment]
I fixed this for the old 0.26 code sample by https://github.com/camunda-cloud/camunda-cloud-documentation/pull/763, but the overall code is no longer in the main docs anyway :-)
