### ISSUE TITLE
Remove extras "Using the BPMN modeler" and "Workflow lifecycle" from bpm pages

### ISSUE THREAD

**Issue by menski** [camunda-cloud/camunda-cloud-documentation#235]

**Comment by menski** [comment]
The reasoning is mainly that the modeler screenshots are updated, and should be updated with the new camunda modeler. In general is the plan to extract the Camunda Modeler docs from the Camunda BPM docs. As their should be shared between Camunda BPM and Camunda Cloud. These docs should be the place where we describe how to model processes, so not duplicate information and increase the maintenance burden.

Regarding the event logs, I assumed after the latest refactoring that they are partially outdated, and didn't saw that we have enough time to update them. Correct me if I'm wrong. We can discuss if we want to readd them but I preferred to not go live with outdated docs.

**Comment by saig0** [comment]
I see your point regarding the modeler. I'm fine if the Zeebe team doesn't need to maintain it. We should just ensure that the users find it easily :+1: 

> I assumed after the latest refactoring that they are partially outdated, and didn't saw that we have enough time to update them

Just a few things changed (assuming that we just document the events) but not so much. I could adjust the docs but we could also do it later. If we remove it then please create a follow-up issue to add it back.

**Comment by menski** [comment]
Follow-up issues after removable are #242 and #243
