### ISSUE TITLE
Include Best Practices Blog Posts links

### ISSUE THREAD

**Issue by akeller** [camunda-cloud/camunda-cloud-documentation#257]
berndruecker is in the middle of creating at least 3 Camunda Cloud Best Practices in the form of blog posts. 

* https://blog.bernd-ruecker.com/drafting-your-camunda-cloud-architecture-connecting-the-workflow-engine-with-your-world-3d94e8d404d6
* To be published - https://blog.bernd-ruecker.com/service-integration-patterns-with-bpmn-and-camunda-cloud-53b0f458e49
* To be written

We need to find a good place to add these blogs for reference.

A future topic of discussion would be splitting the Best Practices into a separate space or including them in the Camunda Platform Best Practices. For now, we will link to them in the docs as blog posts.

**Comment by berndruecker** [comment]
@falko FYI

**Comment by akeller** [comment]
@berndruecker when your 3rd blog is ready to go, be sure to send me the URL or add it here!

**Comment by falko** [comment]
https://blog.bernd-ruecker.com/writing-good-workers-for-camunda-cloud-61d322cad862

**Comment by berndruecker** [comment]
Thanks, Falko! I haven't found back this issue - but created a PR instead: https://github.com/camunda-cloud/camunda-cloud-documentation/pull/316

From my perspective, we could also close this issue now - with the best practices page already existing I am happy to simply provide PR's whenever I think a future blog post from me deserves a mention there. OK?

**Comment by akeller** [comment]
Sounds good! Thank you both :)
