### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/camunda-cloud-documentation#258]
We've come across some dead links. There might be more.

Pages with dead links found:
- https://docs.camunda.io/docs/product-manuals/clients/java-client/job-worker (`BackoffSupplier`, `JobWorkerBuilder`, `gRPC Technical Error Handling`, `backpressure mechanism`)
- https://docs.camunda.io/docs/product-manuals/clients/java-client-examples/job-worker-open (`Source on github`)
- other java-client-examples with `Source on github`

**Comment by akeller** [comment]
Good catch! 

`BackoffSupplier` link as an example-

Current - https://github.com/camunda-cloud/zeebe/blob/develop/clients/java/src/main/java/io/zeebe/client/api/worker/BackoffSupplier.java
Valid - https://github.com/camunda-cloud/zeebe/blob/develop/clients/java/src/main/java/io/camunda/zeebe/client/api/worker/BackoffSupplier.java

Looks like` /camunda/ `was added to the path.

Same for [JobWorkerBuilder](https://github.com/camunda-cloud/zeebe/blob/develop/clients/java/src/main/java/io/camunda/zeebe/client/api/worker/JobWorkerBuilderStep1.java).

**Comment by akeller** [comment]
For gRPC error handling - https://docs.camunda.io/docs/reference/grpc#technical-error-handling

**Comment by korthout** [comment]
> Looks like/camunda/was added to the path.

@akeller That's correct

**Comment by korthout** [comment]
> Good catch!

Kudos to @that-one-tom

**Comment by akeller** [comment]
Backpressure mechanism - https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/operations/backpressure

**Comment by akeller** [comment]
Making these changes today, I noticed https://docs.camunda.io/docs/product-manuals/clients/java-client/job-worker/ is not actually available in the left-hand directory. How did you find this page @korthout, with search?

**Comment by korthout** [comment]
> How did you find this page?

I think it was with search, but it's also referred in the bottom of https://docs.camunda.io/docs/product-manuals/clients/java-client/index/
