### ISSUE TITLE
Update Zeebe deployment guide to version 1.0

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/camunda-cloud-documentation#266]
# Product Manuals > Zeebe > Deployment guide > Getting started tutorial > Tutorial setup

[This tutorial](https://docs.camunda.io/docs/product-manuals/zeebe/deployment-guide/getting-started/tutorial-setup/) is based around an old version of zeebe (0.20). However, for a user it is hard to migrate from 0.20 to 1.0. They would be setting up things using configurations that no longer exists, using an old elastic search version, etc.

Let's update this guide to 1.0.

**Comment by Zelldon** [comment]
Not sure what was the state before but it is still referencing elastic 6.8

@akeller do we have any plans on this?

**Comment by Zelldon** [comment]
Always fine with deleting stuff it makes things easier

**Comment by akeller** [comment]
I'll review (merge into existing guide if needed) and delete it with my upcoming docs changes.
