### ISSUE TITLE
Old Zeebe docs seem to still be available 

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/camunda-cloud-documentation#268]
It seems the old zeebe docs are still available under https://stage.docs.zeebe.io/ and don't forward to https://docs.camunda.io/ like https://docs.zeebe.io/ does.

**Comment by akeller** [comment]
https://stage.docs.zeebe.io/ is indexed by Google as well. If there is a need to keep this environment up, we'll need to noindex or add a robots.txt to stop the crawler.

**Comment by korthout** [comment]
I don't think there's a need to keep this environment up, since all docs are now in https://docs.camunda.io. But, I don't own that url so let's find out who does.

**Comment by akeller** [comment]
@menski took care of the zombie process. While the results on Google still show URLs to stage, they are all redirecting to docs.camunda.io. IMO we can close this now.

**Comment by korthout** [comment]
Thanks!
