### ISSUE TITLE
Update Guide has wrong url for 026 to 100

### ISSUE THREAD

**Issue by felix-mueller** [camunda-cloud/camunda-cloud-documentation#269]
When opening https://docs.camunda.io/docs/1.0/guides/update-guide/introduction/ somehow sometimes the link to 0.26 -> 1.0 is dead, it sometimes points to https://docs.camunda.io/docs/1.0/guides/update-guide/introduction/026-to-100 instead of https://docs.camunda.io/docs/1.0/guides/update-guide/026-to-100
The side bar navigation however seems to work most of the times.

Sounds like URL slugs are causing problems

**Comment by akeller** [comment]
I haven't been able to get this to fail since you reported it. Is this still a problem you can reproduce?

**Comment by akeller** [comment]
Nevermind, this is the trailing slash problem like #304

**Comment by akeller** [comment]
This is merged in and live. I'm not able to reproduce the slash after adding the config. I'll also make sure we cleanup any links in that may include a trailing slash and get those removed.
