### ISSUE TITLE
Make the difference between Self-Managed vs. SaaS in terms of updates more clear

### ISSUE THREAD

**Issue by felix-mueller** [camunda-cloud/camunda-cloud-documentation#270]
The page https://docs.camunda.io/docs/1.0/guides/update-guide/026-to-100 is very detailed which is very good for Self-Managed users.
For SaaS users it is a bit confusing since there are many steps which they don't have to do. 
We should somehow make clear what SaaS users have to do vs. Self-Managed users.
This would make it way easier to consume for many of our users.

**Comment by felix-mueller** [comment]
@akeller I guess this will happen as part of implementing your vision around Cloud Documentation? Or can we have this for 1.2 already?

**Comment by akeller** [comment]
Yes, this is baked in @felix-mueller. I'll close it when its implemented 😄
