### ISSUE TITLE
The search shows duplicated results for different versions

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/camunda-cloud-documentation#280]
When I use the search in the documentation then it shows the same result multiple times. Each entry links to a different version.

![image](https://user-images.githubusercontent.com/4305769/122224593-8bcf8400-ceb4-11eb-8174-c860e01ffc50.png)

As a user, this looks confusing and it doesn't show the version of the entry.

We could solve this problem by enabling the following feature: https://docusaurus.io/docs/search#contextual-search
If enabled then the search shows only the results of the selected version.

**Comment by saig0** [comment]
@akeller do you agree with the problem? what do you think about enabling the feature?

**Comment by akeller** [comment]
This does look like a problem. Looks like Contextual Search would be a great add!

I'm not very familiar with Algolia configuration, but I know we currently use a custom index. Do you have any insight into why?

**Comment by saig0** [comment]
No, I'm not aware that we use a custom index. 

In the configuration, I only see that we use Algolia but the feature is disabled.

https://github.com/camunda-cloud/camunda-cloud-documentation/blob/master/docusaurus.config.js#L137-L141

**Comment by akeller** [comment]
Ok, let's get this enabled and see if this improves search!
