### ISSUE TITLE
I can read about business rule tasks, script tasks, and send tasks

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/camunda-cloud-documentation#295]
* update the BPMN coverage with the new supported elements: business rule task, script task, and send task
* create new reference pages for the new task types

**Comment by saig0** [comment]
Related to 
* camunda-cloud/zeebe#7155
* camunda-cloud/zeebe#7156
* camunda-cloud/zeebe#7157

**Comment by akeller** [comment]
PR was merged, closing this!
