### ISSUE TITLE
Camunda Cloud doc search is not usable

### ISSUE THREAD

**Issue by Zelldon** [camunda-cloud/camunda-cloud-documentation#309]
Currently it seem to show no results at all. 

![job](https://user-images.githubusercontent.com/2758593/125298486-779e6b80-e328-11eb-9548-8feb97152caf.png)
![zeebe](https://user-images.githubusercontent.com/2758593/125298492-78370200-e328-11eb-930f-f87110c8b5ea.png)

No matter what type of keyword I type into.

**Comment by akeller** [comment]
I believe this has to do with the contextual search config we enabled late last week. 

`contextualSearch: true,`

I have opened a PR to modify the DocSearch config to add `docusaurus_tag` to `attributesForFaceting`.

**Comment by akeller** [comment]
Looks good after modifications to the docsearch-configs Algolia maintains!
