### ISSUE TITLE
Defects after migration of Zeebe documentation

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/camunda-cloud-documentation#37]
This is the list of known defects after migration of the Zeebe documentation:

* Logo on start page of Zeebe section is not centered
* Page "BPMN Coverage" had a nice overview, which was a labor of love. However, the new documentation tool is very strict about embedded HTML and I couldn't get it to work. The original stuff is in the file as HTML comment. I added a simple list instead.
* Links that pointed to files of the same commit in the same repository were replaced by links to develop head (
`https://github.com/zeebe-io/zeebe/tree/{{commit}}/exporters/elasticsearch-exporter` -> `https://github.com/zeebe-io/zeebe/tree/develop/exporters/elasticsearch-exporter`); this might need to be reconsidered when the versioning strategy is finalized. 
* Includes of files in the same repository (`{{#include ../../../dist/src/main/config/application.yaml}}`) have been removed , unfortunately. I did not find a ready alternative. The originals are still in the files as html comments
* many images are not suitable for dark mode
* (Fixed) in the old documentation the MP4 videos started to play automatically; in the new documentation the user has to start the videos manually. And it is not obvious that they are videos you can play.-

**Comment by akeller** [comment]
Closing this issue. For complete transparency, I'm looking to move all modeling documentation in the future to Camunda Modeler docs as the "source of truth". Maybe this way we make enabling dark mode easier 😅
