### ISSUE TITLE
Document new experimental configuration options in Zeebe

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/camunda-cloud-documentation#38]
**Description**

We've added a new experimental configuration section in Zeebe for incubating features, or dangerous features. This gives power users further options to customize Zeebe to their needs, and lets us test new features, while also freeing us from long term support of these: anything under the experimental section is subject to be dropped or to change in the future.

We should document this explicitly, and also document the flags that are currently listed there.

P.S.: let me know if this is the wrong place for these kind of issues :slightly_smiling_face:

**Comment by akeller** [comment]
Do we still have this excitingly dangerous feature ability that we need to document? 😄

**Comment by npepinpe** [comment]
Yes, and I would say it's becoming more and more important to do so :sweat_smile:
