### ISSUE TITLE
GH-Pages Prod-Build returns warning after datacenter switch

### ISSUE THREAD

**Issue by Sijoma** [camunda-cloud/camunda-cloud-documentation#385]
We receive the following warning for the production build. This occurs after the switch to the new datacenter in Frankfurt. 

> The page build completed successfully, but returned the following warning for the `gh-pages` branch:
> 
> Your site's DNS settings are using a custom subdomain, docs.camunda.io, that's set up as an A record. We recommend you change this to a CNAME record pointing at camunda-cloud.github.io. For more information, see https://docs.github.com/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site.
> 
> For information on troubleshooting Jekyll see:
> 
>  https://docs.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can submit a request at https://support.github.com/contact?tags=dotcom-pages&repo_id=296602422&page_build_id=285671274

**Comment by menski** [comment]
I removed the workflow, deleted the `gh-pages` branch and deleted the gh-pages settings in this org. Let's just hope the datacenter deployment works :crossed_fingers:
