### ISSUE TITLE
Document maximum message / payload size

### ISSUE THREAD

**Issue by felix-mueller** [camunda-cloud/camunda-cloud-documentation#396]
A user got the following error: "gRPC message exceeds maximum size 4194304: 5041972"
I was wondering where to best point them in our docs and could not find anything.

https://github.com/camunda-cloud/zeebe/blob/develop/dist/src/main/config/broker.standalone.yaml.template#L141-L143
https://docs.camunda.io/docs/components/zeebe/deployment-guide/configuration/configuration/#configuration-file-templates

@Zelldon mentioned "I think in general it would be good thing to document, but not 100% sure where the right place is. It affects many places and this is also really the max, but it could be that the user already hits a lower bar via deployment or variables, since we have metadata etc we have to store as well and need to fit in these 4 MB."

**Comment by akeller** [comment]
We should have a broader conversation about where to put log level documentation. I've added it to the Cloud stakeholder meeting for this week.

You linked to a deployment guide - would this only impact CCSM users? Or would CCSM users be the only ones who could mitigate it? Or is it even possible to mitigate it given that it's the max?

**Comment by berndruecker** [comment]
Also discussed internally: https://camunda.slack.com/archives/CHBFBRFM2/p1647275864961669

I think this is not related to installation, but generally how much data you can put into the platform.

**Comment by berndruecker** [comment]
Created https://github.com/camunda-cloud/camunda-cloud-documentation/pull/767 for this

**Comment by berndruecker** [comment]
Fixed with #767
