### ISSUE TITLE
Broken link in getting started

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/camunda-cloud-documentation#419]
The getting started contains a broken link. Specifically it is the link in the top of the page of: https://docs.camunda.io/docs/guides/getting-started/implement-service-task/. I believe it is supposed to refer to https://github.com/camunda-cloud/camunda-cloud-documentation/blob/master/docs/guides/getting-started/bpmn/gettingstarted_quickstart_advanced.bpmn

**Comment by akeller** [comment]
@christinaausley is this the same issue as the others with the trailing slash on the new infrastructure?

**Comment by christinaausley** [comment]
@akeller Yes -- @menski is testing out a few options to resolve.
