### ISSUE TITLE
I can read how to model a DMN

### ISSUE THREAD

**Issue by saig0** [camunda-cloud/camunda-cloud-documentation#422]
With Zeebe 1.3, we implement that a business rule task can evaluate a DMN decision.

We should add a new section to the reference for DMN. It should describe what parts of DMN are supported, how to use a decision table, and how to use a literal expression. 

It may look similar to https://docs.camunda.org/manual/7.16/reference/dmn/. Since Zeebe uses a different DMN engine, we can't copy the content completely.

We need to think about where to store the documentation. The FEEL docs are located in the FEEL-Scala project and are copied into the docs. For DMN it is kind of similar because we will share the same DMN engine with Camunda Platform 7.

**Comment by akeller** [comment]
@christinaausley's tasked with creating a platform agnostic guide for DMN which will likely cover "how to use a decision table". When this is closer to being complete on the engineering side, can you sync with us on how to document this experience?

**Comment by saig0** [comment]
@akeller just to make it clear, who should write the documentation for DMN? the engineering team? what is the concrete task of @christinaausley?

**Comment by akeller** [comment]
We are moving Modeler documentation from docs.camunda.org to docs.camunda.io, which will include DMN but will be marked "Platform-only". You can see that work on #415. 

@christinaausley will work on drafting guides for BPMN, DMN, and forms reusing some existing content. These guides will be agnostic if possible, meaning they should apply to both Cloud and Platform where possible. 

The engineering team should plan to write the rest of the DMN documentation, including reviewing the DMN guide to make sure functionality added to Cloud works as documented.

**Comment by saig0** [comment]
@akeller thank you for the information :+1: 

When can we expect the agnostic DMN documentation from @christinaausley? 
We want to launch DMN in Camunda Cloud with version `1.4` (end of Q1 2022). For the release, we should have a DMN doc for the users.

**Comment by akeller** [comment]
That should be in line with what @christinaausley can do 🙂

**Comment by korthout** [comment]
Ping @barmac, just to keep you in the loop

**Comment by barmac** [comment]
Probably this is not part of this issue, but it's related to the DMN documentation. At camunda.com, user can download a DMN Cheatsheet. The cheatsheet is Camunda DMN-specific, e.g.
![image](https://user-images.githubusercontent.com/28307541/155963966-bee95529-5df1-40f4-a60c-f710bb1b36f7.png)
 or
![image](https://user-images.githubusercontent.com/28307541/155964012-0259c090-d934-425c-aa53-130e1105f925.png)

Perhaps it makes sense to update the cheatsheet once DMN is supported in the Cloud.

**Comment by santanaluiz** [comment]
@akeller is the DevRel team planning to create any documentation about Operate usage as well?

**Comment by akeller** [comment]
> @akeller is the DevRel team planning to create any documentation about Operate usage as well?

@santanaluiz In terms of DMN? 

I have nothing in the DX backlog, but @Hafflgav or @jwulf do either of you have plans for official or unofficial docs for Operate?

**Comment by akeller** [comment]
> Probably this is not part of this issue, but it's related to the DMN documentation. At camunda.com, user can download a DMN Cheatsheet. The cheatsheet is Camunda DMN-specific, e.g. ![image](https://user-images.githubusercontent.com/28307541/155963966-bee95529-5df1-40f4-a60c-f710bb1b36f7.png) or ![image](https://user-images.githubusercontent.com/28307541/155964012-0259c090-d934-425c-aa53-130e1105f925.png)
> 
> Perhaps it makes sense to update the cheatsheet once DMN is supported in the Cloud.

@barmac can you link me to this cheatsheet? I can work with the marketing team to update it.

**Comment by barmac** [comment]
Sure, it's available at https://page.camunda.com/wp-dmn-cheat-sheet

**Comment by saig0** [comment]
Done by #775
