### ISSUE TITLE
Document user task assignments

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/camunda-cloud-documentation#454]
Camunda Cloud 1.3 will support `assignee` and `candidateGroups` properties for user tasks.

New documentation will need to be added to describe :
- how users can define these properties
- ~how Zeebe deals with incorrect usage and evaluation failures (i.e. both can be expressions, whose evaluation can fail)~, usually this is not documented
- how both values are exposed in the Tasklist API (and potentially how the assignee is directly influencing task assignment in Tasklist)

## Issue Tracking

- [x] #463 
- [x] #458

**Comment by korthout** [comment]
@MaxTru Do we already have any new documentation for the Modeler part of this?

@sdorokhova Do we already have any documentation for the Tasklist part of this?

**Comment by MaxTru** [comment]
Modeler perspective:

* There are two areas of Modeler documentation at the moment:
  * https://docs.camunda.io/docs/components/modeler/camunda-modeler/model-your-first-diagram/
    * Written by Cloud team
  * https://docs.camunda.org/manual/7.16/modeler/
    * Written by Modeler Team
    * Will be migrated to Cloud soon (DRI @akeller)
* Neither of the mentioned documentation areas go on a detailled "this is how you configure property xyz" level. Hence => given our current strategy, I don't see the need for documentation from Modeler perspective.

**Comment by sdorokhova** [comment]
Here is the issue for Tasklist: https://github.com/camunda-cloud/camunda-cloud-documentation/issues/458
