### ISSUE TITLE
Responsiveness problem with navigation bar

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/camunda-cloud-documentation#475]
I've found that a specific page width has not enough space to fit all the navigation items.

We should switch to hamburger menu at a higher width threshold.

|Title|Screenshot|
|----|---------|
|Wide view with normal layout|![Screen Shot 2021-12-02 at 11 05 42](https://user-images.githubusercontent.com/3511026/144401785-9e845729-4bd3-40f8-900a-eaf953054807.png)|
|Too tight, items get squashed|![Screen Shot 2021-12-02 at 11 05 36](https://user-images.githubusercontent.com/3511026/144402053-0929d5c8-0f0c-4df1-b91c-63348e551f15.png)|
|Tight view with hamburger menu|![Screen Shot 2021-12-02 at 11 05 49](https://user-images.githubusercontent.com/3511026/144402117-2dcc7aac-c03d-43ae-adb5-af213212ab07.png)|

**Comment by akeller** [comment]
@pepopowitz would you consider this fixed with your PR for #816? If yes, please close this issue!

**Comment by pepopowitz** [comment]
Yes! This is fixed with #816.

**Comment by korthout** [comment]
Thanks! 👍 Verified on https://docs.camunda.io and works great! 🎉
