### ISSUE TITLE
Authentication section title

### ISSUE THREAD

**Issue by jwulf** [camunda-cloud/camunda-cloud-documentation#493]
[This section of the docs](https://docs.camunda.io/docs/self-managed/zeebe-deployment/security/authentication/
) is called “Authentication”.

Strictly speaking, that is kinda accurate, because it is describing authentication of the server through TLS.

However, most people would think of this as encryption plus maybe server authentication (it’s more like identity validation).

When the audience is thinking Authentication, they are more likely to be thinking of client authentication, ie: “_how do I allow authenticated clients only to perform operations_” .

So I think we should change this section title to “Transport Layer Security”.

**Comment by akeller** [comment]
@menski @pihme any issues with this? I think it makes sense.
