### ISSUE TITLE
Add optimize to https://docs.camunda.io/docs/guides/ overview

### ISSUE THREAD

**Issue by felix-mueller** [camunda-cloud/camunda-cloud-documentation#554]

**Comment by felix-mueller** [comment]
@akeller is this covered in a different somewhere else maybe already that I have overseen?

**Comment by akeller** [comment]
Oh shoot, I forgot that page. Covered the overview pages for Components and Self-Managed but I missed this one. I'll PR and get it added!

**Comment by akeller** [comment]
Committed to master 😈  @menski can you do another release to update this ASAP?

**Comment by akeller** [comment]
Live 🚀
