### ISSUE TITLE
Label "Platform only" might not be self-explanatory

### ISSUE THREAD

**Issue by meyerdan** [camunda-cloud/camunda-cloud-documentation#556]
Hypothesis:

* I can imagine that the label "Platform only" is not self-explanatory for users (no data / anecdotes to back this up as of now).

![image](https://user-images.githubusercontent.com/488063/149119273-b608fa94-d3a0-4784-b7c2-fa448188cfcd.png)

Ideas:

* Rename to "Camunda Platform 7 only"
* Have a page that explains the labels and when I click on the label I get to the definition of the label on that page

**Comment by akeller** [comment]
This badge now says "Camunda Platform 7 only" and I'm drafting a "meta" page that will contain information about how to use the docs, including badges. Thanks @meyerdan!

**Comment by akeller** [comment]
Meta page is on `release-1.4.0`
