### ISSUE TITLE
Document how the gateway forwards a client request to a broker

### ISSUE THREAD

**Issue by McAlm** [camunda-cloud/camunda-cloud-documentation#560]
for jobs and process instances the technical identifier, e.g. process instance key, contains the partition id, therefore the gateway can decode the partition id and reach the correct broker.
For publish message commands the gateway calculate a hash of the correlation key to identify the correct partition to send the message to and in the same way the workflow engine does calculate the hash of the correlation key of messages it awaits find the right partition to correlate the message on.

**Comment by korthout** [comment]
IMO these technical details are not suitable for public documentation. Forwarding requests happens transparently to reduce complexity for the user. The user does not have to know how this works, as long as they can trust that the dedicated Zeebe gateway can reliably forward requests to the correct broker. If we were to document it, we would bind ourselves to that particular implementation. We should avoid that to stay flexible.

I'll close this now, but I'd be happy to hear counterarguments. Please re-open the issue if you believe we should document this
