### ISSUE TITLE
Simplify Supported Environments page

### ISSUE THREAD

**Issue by felix-mueller** [camunda-cloud/camunda-cloud-documentation#561]
https://docs.camunda.io/docs/reference/supported-environments/

Currently supported environments page goes into every component separately. 
We should consider simplifying this. If there are differences, we should really think about the WHY and try to align as much as possible. This might also lead to changes in supported environments in the end.

**Comment by akeller** [comment]
Can I assign this to you @felix-mueller? I really like this idea, but I feel this is a decision that should be made with the product managers for each component, or maybe the overall Cloud PM 😉
