### ISSUE TITLE
Document network compression between Zeebe nodes

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/camunda-cloud-documentation#569]
Please document how to configure network compression between Zeebe nodes, the possible values, when you would pick one or the other, and potential pitfalls.

**Comment by npepinpe** [comment]
The documentation website is the best tool, in my opinion, to discover how to operate and configure your Zeebe installation. True, you could dig into the configuration file, but I'm not sure that's necessarily the first place users will look at after evaluation when trying to discover if someone is configurable in Zeebe.

Additionally, I don't expect the configuration file dig into "when you would pick one or the other, and potential pitfalls", but rather simply to document which configurations are possible and the valid values for the settings; this is something you can write in the documentation.

Does that clarify anything? I understand I have no proof of course, and maybe I'm wrong and configuration templates are how users discover settings/options, and I'm happy to be challenged :smile:

**Comment by deepthidevaki** [comment]
I don't think anyone is looking for "how to enable compression in zeebe". If any one is looking for that it is easy to get that information from the configuration template (which is also linked in the docs). On the other hand a user might be looking for "how to configure zeebe for multi-dc deployment", or "how to performance tune". I think such sections are useful in the docs - which list a set of configuration that might be interesting for the user.

> Additionally, I don't expect the configuration file dig into "when you would pick one or the other, and potential pitfalls",

Most of these information is in the configuration file. If there is anything missing, we can add that there.

**Comment by npepinpe** [comment]
Those are good points, thanks for expanding on your thoughts :slightly_smiling_face: We can close this then.
