### ISSUE TITLE
Consider a "Managing the Client Lifecycle" chapter in the Java API docs

### ISSUE THREAD

**Issue by Camunda-ChrisAllen** [camunda-cloud/camunda-cloud-documentation#574]
Per Daniel, _"The Client should always be closed because it starts background threads which could lead to a resource leak if an application repeatedly opens a client but never closes it."_  

I see this as a gap of "common knowledge" of the product devs that should also be reflected in the docs publicly.

**Comment by berndruecker** [comment]
Looking at it from a Spring angle this is nothing the developer needs to be concerned with. 
Also for pure Java, I don't think this is a big priority, but still it might be a quick win to make a note about it in https://docs.camunda.io/docs/apis-clients/java-client/#bootstrapping?

**Comment by akeller** [comment]
@berndruecker would you be willing to PR your suggested quick win? 😉

**Comment by akeller** [comment]
@berndruecker will you target `release-1.4.0` for this PR? If so I will label it and know to expect it before this release goes live.

**Comment by berndruecker** [comment]
While I was working on this and looking through issues I also clean up https://github.com/camunda-cloud/camunda-cloud-documentation/issues/230 in one go (even if this was only used in very old examples)

**Comment by berndruecker** [comment]
https://github.com/camunda-cloud/camunda-cloud-documentation/pull/763
