### ISSUE TITLE
Document usage metrics

### ISSUE THREAD

**Issue by santanaluiz** [camunda-cloud/camunda-cloud-documentation#597]
## Description

We need to document the usage metric endpoints create for Operate and tasklist.

## Endpoints

We have 2 endpoints at the moment (v 1.3.x).

NOTE: those endpoints run on `actuator` endpoints so they can be protected by IT team if needed

### Number of process instances completed

This endpoint list the number of process instances successfully executed in the given period.

Endpoint:
`https://OPERATE_URL:OPERATE_PORT/actuator/usage-metrics/process-instances?startTime={startTime}&endTime={endTime}`

Sample date format: 
`1970-11-14T10:50:26.963-0100` or `yyyy-MM-dd'T'HH:mm:ss.SSSZZ`

Sample response:
```json
{
    "total" : 99
}
```

### Number of unique users assigned to tasks 

This endpoints return the number of unique users assigned to tasks in a given period and each of the unique `usernames`.

The reason why it returns also the `usernames` is so that we are able to reconcile in case of multiple instances

Endpoint:
`httsp://TASKLIST_URL:TASKLIT_PORT/actuator/usage-metrics/assignees?startTime={startTime}&endTime={endTime}`

Sample date format: 
`1970-11-14T10:50:26.963-0100` or `yyyy-MM-dd'T'HH:mm:ss.SSSZZ`

Sample response:

```json
{
    "total" : 2,
    "assignees": [
        "john.lennon", 
        "oprah.winfrey"
    ]
}
```

**Comment by santanaluiz** [comment]
@akeller @christinaausley I just added this issue.

But I don't know where it is better to document this and how.
AFAIK, it is something to be used mostly over On-Prem customers, but not sure.

Would you have any suggestion?

**Comment by akeller** [comment]
Hi @santanaluiz I have some questions.

Overall this looks like API reference docs, is that correct? Will this be a full REST API in the future? I don't see anything mentioned about how to connect. 

You also mentioned these run on actuator endpoints to be controlled by IT if needed. I assume that's a customer's IT team based on your On-Prem customer comment. So this would be something Tasklist and Operate would use in CCSM only? 

Feel free to setup some time with me if you'd rather discuss over a call but it sounds like we could put this in the CCSM section of the docs, but make a note in the APIs & Clients section if anyone is looking for this information to help them find it.

**Comment by santanaluiz** [comment]
This is just an API used eventually to retrieve usage metrics. So the customer can report to us and we are able to charge them (self managed/on-prem customer).
So about your question:

> So this would be something Tasklist and Operate would use in CCSM only?

That's right.

Okay, CCSM is what I had in mind. I will set up something and assign to @christinaausley  to review.
Thanks :)
