### ISSUE TITLE
[PLACEHOLDER] Document back up procedure used by Camunda Cloud in a cloud agnostic way

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/camunda-cloud-documentation#60]
**Description**

We will work on an offline backup solution for Camunda Cloud centered around the upgrade procedure. If at all possible once a solution is fixed, let's evaluate the pros and cons of documenting it for on-prem users.

- How portable is our solution?
- Can we write it in a Kubernetes generic way, e.g. ignoring GCP?

We'll probably need help from the Cloud SRE team :slightly_smiling_face:

**Comment by akeller** [comment]
Closing this, need to think through this more internally first.
