### ISSUE TITLE
Guide "Building forms with Modeler" only features "Web Modeler" and not "Desktop Modeler" way

### ISSUE THREAD

**Issue by MaxTru** [camunda-cloud/camunda-cloud-documentation#611]
**What**

The guide ["Building forms with Modeler"](https://docs.camunda.io/docs/guides/utilizing-forms/#connect-your-form-to-a-bpmn-diagram) only features / explains how to connect to forms the "Web Modeler" and not the "Desktop Modeler" way.

**Solution I'd like**

Have two sections or two labels / tags of that guide, one for the Desktop and one for the Web Modeler.

**Alternatives considered**

Only feature the Web Modeler way (maybe right priorty?)

**Comment by akeller** [comment]
For our Guides content, I want to intentionally be SaaS first, including the components. This doesn't mean I don't want to document the Desktop way, but I do want to include it as part of the next step or additional resources at a minimum.

Let's get the Desktop way documented in the Components section of the docs and make sure we link to it from the Guide as an alternative way to work with forms. We could also look into including a link at the beginning of the Guide for folks who may already be more comfortable in the Desktop experience. WDYT?

**Comment by MaxTru** [comment]
Makes sense. Closing this then.
