### ISSUE TITLE
Description of GraphQL endpoint URL

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-cloud/camunda-cloud-documentation#629]
As a developer, I might overread the dialogue on client secret creation (or I do not create the secret on my own). So, I would expect to find the GraphQL endpoint URL stated like `https://${REGION}.tasklist.camunda.io:443/${CLUSTER_ID}/graphql`.

I would expect to find this endpoint somewhere [here](https://docs.camunda.io/docs/components/tasklist/userguide/api/overview/) containing a hint that this applies for the CCSaas version.

**Comment by akeller** [comment]
@ralfpuchert can you have a look at this? Is this covered in your updates in `release1.4.0`? 

I'm realizing I didn't do a review and the API content for Tasklist is likely better housed in the APIs & Clients section of the docs than the Components section. WDYT?

**Comment by ralfpuchert** [comment]
Hi, thanks for raising this. Good point.
I think we should move the API content for Tasklist to the APIs & Clients section. I'll prepare a PR for it.
