### ISSUE TITLE
Review Best Practices & format for style guide

### ISSUE THREAD

**Issue by akeller** [camunda-cloud/camunda-cloud-documentation#636]
Due to scheduling and higher priority work, we will merge #625 without a full editorial review. 

@christinaausley please keep this in mind if you have time through the end of the quarter or going into Q2.

**Comment by berndruecker** [comment]
@christinaausley Let me know how we should best organize this. Start an own branch? 

I also need to prepare the renaming branch soon - so we need to coordinate a bit to not intervene :-)

**Comment by christinaausley** [comment]
Per @berndruecker and I's Slack discussion, we'll create one branch. I'll plan to finish up the remaining Best Practices over the next few weeks so Bernd will have a good chunk of March for renaming.

I've opened up a branch called `docs-bestpractices` to work in.
