### ISSUE TITLE
Update Review Process

### ISSUE THREAD

**Issue by akeller** [camunda-cloud/camunda-cloud-documentation#637]
As documented in the Review Process we have the following folks listed:

Cloud: @urbanisierung
Zeebe: @pihme
Operate/Tasklist: @ralfpuchert
DevRel: @akeller
Product Management: @felix-mueller
Fallback: @menski

Does this still make sense? Or should we swap in @ultraschuppi and @santanaluiz for their respective components? Should we also add @christinaausley as a reviewer for documentation (with me as a fallback)?

**Comment by ultraschuppi** [comment]
> Does this still make sense? Or should we swap in @ultraschuppi and @santanaluiz for their respective components? Should we also add @christinaausley as a reviewer for documentation (with me as a fallback)?

i guess i should be the sheriff and @urbanisierung the deputy  - but not sure if _Cloud_ is the right term, as it is a bitch of catch-all

**Comment by akeller** [comment]
😆  great typo, maybe me LOL

Do you think "Console" is more aligned? And in that sense should we also add someone from Modeler? Or would you cover that as well? 

And we need to add Optimize! 🙊

**Comment by ultraschuppi** [comment]
oh dear, auto-cowrecked - i fixed it ;)

console seems fine

**Comment by pihme** [comment]
I'd like to swap my name for the Zeebe part with @npepinpe He has the better overview of all the changes.

**Comment by akeller** [comment]
Updates so far: 

Console: @ultraschuppi 
Zeebe: @npepinpe 
Operate/Tasklist: @ralfpuchert
Optimize: @megglos
DevRel: @akeller
Product Management: @felix-mueller
Fallback: @menski

Documentation review: @christinaausley (fallback: @akeller)

**Comment by akeller** [comment]
^ Any objections? Otherwise, I'll PR.
