### ISSUE TITLE
Element Template link is broken

### ISSUE THREAD

**Issue by marstamm** [camunda-cloud/camunda-cloud-documentation#659]
The link under https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/#learn-more redirects to https://github.com/camunda/desktop-modeler/tree/master/docs/element-templates , which does not exist.

It should be [https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates](https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates) (camunda-modeler vs. desktop-modeler). This looks like a "find and replace" bug, so other links might be affected as well

**Comment by akeller** [comment]
Good catch. Will the GitHub repo remain `camunda-modeler` or will it also be renamed in the future?

**Comment by akeller** [comment]
@christinaausley can you look into this?

**Comment by marstamm** [comment]
There are no plans to rename the technical labels (like the repo name) at the moment
