### ISSUE TITLE
Clarify recommendation for production environments

### ISSUE THREAD

**Issue by berndruecker** [camunda-cloud/camunda-cloud-documentation#670]
See https://camunda.slack.com/archives/C02CACNKZDY/p1646641296257389?thread_ts=1645441782.409569&cid=C02CACNKZDY

We need to fix our supported environments and make clear, what we recommend/support self-managed:
- bare metal or VM
- Docker Compose
- Kubernetes

**Comment by berndruecker** [comment]
Pinging @felix-mueller @menski

**Comment by akeller** [comment]
@berndruecker can I assign this to you? I saw you asking more questions internally for clarification.

**Comment by berndruecker** [comment]
Pages:

- https://docs.camunda.io/docs/self-managed/zeebe-deployment/local/install/
- https://docs.camunda.io/docs/self-managed/zeebe-deployment/local/quickstart/ -> to be removed
- https://docs.camunda.io/docs/self-managed/zeebe-deployment/docker/install/
- https://docs.camunda.io/docs/self-managed/zeebe-deployment/kubernetes/ -> not only for Zeebe, but all components
- https://docs.camunda.io/docs/self-managed/zeebe-deployment/kubernetes/helm/installing-helm/
- https://docs.camunda.io/docs/self-managed/zeebe-deployment/kubernetes/helm/accessing-operate-tasklist/

Related:
- https://docs.camunda.io/docs/reference/supported-environments/
- https://docs.camunda.io/docs/components/best-practices/architecture/deciding-about-your-stack/#running-camunda-cloud-self-managed

**Comment by berndruecker** [comment]
Related to https://github.com/camunda-cloud/camunda-cloud-documentation/issues/640

**Comment by berndruecker** [comment]
Implemented with https://github.com/camunda-cloud/camunda-cloud-documentation/issues/640 - so closing this now
