### ISSUE TITLE
Broken in links in release-1.4.0 branch

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/camunda-cloud-documentation#676]
There is broken links in the current release-1.4.0 branch. PR's targeting this branch are failing as a result of this (e.g. https://github.com/camunda-cloud/camunda-cloud-documentation/pull/507):

```
Provided URLs failing:
http://172.17.0.2:8080/docs/components/modeler/desktop-modeler/element-templates/about-templates/ (HTTP 404)
http://172.17.0.2:8080/docs/components/modeler/desktop-modeler/element-templates/additional-resources/ (HTTP 404)
http://172.17.0.2:8080/docs/components/modeler/desktop-modeler/element-templates/configuring-templates/ (HTTP 404)
http://172.17.0.2:8080/docs/components/modeler/desktop-modeler/element-templates/defining-templates/ (HTTP 404)
http://172.17.0.2:8080/docs/components/modeler/desktop-modeler/element-templates/using-templates/ (HTTP 404)
http://172.17.0.2:8080/docs/components/modeler/desktop-modeler/flags/ (HTTP 404)
http://172.17.0.2:8080/docs/components/modeler/desktop-modeler/plugins/ (HTTP 404)
http://172.17.0.2:8080/docs/components/modeler/desktop-modeler/search-paths/ (HTTP 404)
http://172.17.0.2:8080/docs/components/modeler/desktop-modeler/telemetry/ (HTTP 404)
http://172.17.0.2:8080/docs/components/modeler/forms/camunda-forms-reference/ (HTTP 404)
http://172.17.0.2:8080/docs/guides/getting-started-orchestrate-human-tasks/ (HTTP 404)
http://172.17.0.2:8080/docs/self-managed/tasklist-deployment/tasklist-api/ (HTTP 404)
```

There are no failing links on the master branch so it might be a matter of merging this into the 1.4.0 branch (not sure what the release process is here).

**Comment by akeller** [comment]
I'll take care of it 😄 

The link check looks against prod, not the links as they exist in the branches.

**Comment by akeller** [comment]
I took care of all these broken links, but there is one new one 404ing - `feel/language-guide/feel-expressions` was deleted in favor of `feel/language-guide/feel-expressions-introduction`. I put in a redirect, but because this change is not on `master` yet, it will continue to break the build. 

FYI @menski

**Comment by akeller** [comment]
I did a "workaround" and have the deleted page redirecting to an existing page and left a note to myself to change it later. Your builds against `release-1.4.0` should pass now, unless there are actual build issues 🎉
