### ISSUE TITLE
.dmn files are not found in "Choosing the DMN Hit Policy"

### ISSUE THREAD

**Issue by fishtrees** [camunda-cloud/camunda-cloud-documentation#709]
.dmn files are not found in "Choosing the DMN Hit Policy"
https://docs.camunda.io/docs/components/best-practices/modeling/choosing-the-dmn-hit-policy/

so, no decision table shows.

https://docs.camunda.io/bpmn/choosing-the-dmn-hit-policy-assets/unique.dmn
https://docs.camunda.io/bpmn/choosing-the-dmn-hit-policy-assets/customer-discount.dmn
https://docs.camunda.io/bpmn/choosing-the-dmn-hit-policy-assets/customer-creditworthiness-hard.dmn
https://docs.camunda.io/bpmn/choosing-the-dmn-hit-policy-assets/order-review-groups.dmn
https://docs.camunda.io/bpmn/choosing-the-dmn-hit-policy-assets/customer-creditworthiness-soft.dmn

**Comment by akeller** [comment]
@berndruecker can you please take a look here?

**Comment by berndruecker** [comment]
My bad - I will fix it right away

**Comment by berndruecker** [comment]
@akeller do I need to merge this into https://github.com/camunda-cloud/camunda-cloud-documentation/tree/release-1.4.0 too? 
Shall I trigger a redeployment to get changes live?

**Comment by akeller** [comment]
I'll handle the merge to the release branch. Release started, changes should be up in production soon.
