### ISSUE TITLE
Review: Cloud Console

### ISSUE THREAD

**Issue by urbanisierung** [camunda-cloud/camunda-cloud-documentation#73]
Camunda Cloud has of course already been described as Cloud First by his nature. Here are the sections that in my opinion should be adapted:

| Page | Comment | Recommendation |
|--|--|--|
| [Cloud Console Overview](https://docs.camunda.io/docs/product-manuals/cloud-console/overview) | Current description should be part of the overall introduction. On this page I see just an overview of what can be done in Camunda Cloud Console | @akeller move to introduction, @urbanisierung rewrite |
| [Available Plans](https://docs.camunda.io/docs/product-manuals/cloud-console/manage-plan/available-plans) | is this something that should be on top level? | From my pov we can leave the pages as they are for now but I think in a target picture we need a better place for this description. @akeller @meyerdan wdyt? -Daniel agrees

Proposal for new structure:
- [x] Product Manuals/Cloud Console
  - [x] Introduction
  - [x] Create Camunda Cloud Account
  - [x] Manage your Organization
    - [x] Organization Settings
    - [x] Manage Users of your Organization
    - [x] View Organization Activity
    - [x] Manage Cloud Management API
    - [x] Update Billing Reservations
    - [x] Switch Organization
  - [x] Manage your Clusters
    - [x] Create a Cluster
    - [x] Rename your Cluster
    - [x] Delete your Cluster
    - [x] Manage API Clients
  - [x] Manage your Plan
    - [x] Available Plans
    - [x] Trial Plan
    - [x] Professional Plan
      - [x] Upgrade to Professional Plan
      - [x] Billing Parameters
  - [x] Troubleshooting
    - [x] Common Pitfalls
    - [x] Feedback and Support

**Comment by akeller** [comment]
This was moved to Done, closing!
