### ISSUE TITLE
SM section has reference to Optimize License

### ISSUE THREAD

**Issue by Camunda-ChrisAllen** [camunda-cloud/camunda-cloud-documentation#769]
Any reference to an Optimize license for C8SM is confusing.  My understanding is that the whole C8SM product suite is free for non-prod use, and that would include Optimize.  Suggest it be removed.

https://docs.camunda.io/docs/self-managed/optimize-deployment/setup/optimize-license/

I would also hope that any page that is tagged "Camunda Platform 7 only" be removed from Camunda 8 docs.

**Comment by akeller** [comment]
Hi @Camunda-ChrisAllen - we moved all Optimize documentation into docs.camunda.io, so the pages tagged for C7 will remain in this documentation. 

@felix-mueller can you take a look at the feedback on the Optimize license?
