### ISSUE TITLE
IAM requirements are added to Supported Environments (and IAM renamed to Identity)

### ISSUE THREAD

**Issue by berndruecker** [camunda-cloud/camunda-cloud-documentation#772]
https://docs.camunda.io/docs/reference/supported-environments/ should also mention requirements / supported environments for the IAM component (especially PostgreSQL version from what I am seeing).

Maybe @ralfpuchert knows?

**Comment by ralfpuchert** [comment]
I think @Ben-Sheppard or @dlavrenuek can contribute to that topic

**Comment by felix-mueller** [comment]
@dlavrenuek do you plan to add this to the 1.4 branch?

**Comment by berndruecker** [comment]
Could we update IAM to Identity already?
"IAM (Java Application, requiring PostgreSQL)" -> "Identity (Java Application, requiring Keycloak and PostgreSQL)

**Comment by ralfpuchert** [comment]
On https://c8.docs.camunda.io/docs/self-managed/overview/ we don't have `IAM` anymore. AFAIK `IAM` it is replaced by `Identity` from c8 on.

**Comment by dlavrenuek** [comment]
@berndruecker IAM was already replaced by Identity in [1.4.0](https://github.com/camunda-cloud/camunda-cloud-documentation/tree/release-1.4.0), the only requirement we have is `Keycloak`. The users can use any database that is supported by Keycloak and Identity itself does not have a database.

@felix-mueller I will add the supported environment section for Identity since @Ben-Sheppard is out of office till the end of week

**Comment by berndruecker** [comment]
OK, I will:

- swap IAM with Identity in all places (e.g. https://c8.docs.camunda.io/docs/self-managed/overview/, https://c8.docs.camunda.io/docs/self-managed/platform-deployment/)
- Move the Installation part around Docker to https://c8.docs.camunda.io/docs/self-managed/platform-deployment/docker/

Questions to
- @dlavrenuek: We still need information on the supported environments for Identity on https://c8.docs.camunda.io/docs/reference/supported-environments/ - can you give me the information what to add there? Is it simply Keycload in exactly this version for now? 
```
jboss/keycloak:16.1.1
```
- @Zelldon: It looks like the Helm charts can also install Identity, but I am not sure if they do by default? Maybe we should make a note in the docs then. However, this picture seem to be outdated and should probably be updated? https://c8.docs.camunda.io/docs/self-managed/platform-deployment/kubernetes-helm/#components-installed-by-the-helm-charts

**Comment by Zelldon** [comment]
Hey @berndruecker the charts install per default identity. I'm working on configuring operate and tasklist so everything is setup per default. 

I already updated the image here https://helm.camunda.io/ you can just take it from the repo if you want.

**Comment by dlavrenuek** [comment]
@berndruecker exactly, at the moment we officially only support `Keycloak 16.1.1`.

**Comment by berndruecker** [comment]
Ok great! will take that picture @Zelldon and add the requirements @dlavrenuek - thanks!

**Comment by berndruecker** [comment]
Should be all fixed with https://github.com/camunda-cloud/camunda-cloud-documentation/pull/781

**Comment by berndruecker** [comment]
Ok - great. Sounds super. Will take the pic from there

Sent from a mobile device
________________________________
