### ISSUE TITLE
Rewrite Operate Userguide

### ISSUE THREAD

**Issue by meyerdan** [camunda-cloud/camunda-cloud-documentation#84]
The current user guide for Operate does not accurately reflect the main usecases users can complete with the product.
Also, it does not provide a structure that we can build upon for the future.

ACs:
- We have defined a good structure for the operate userguide that allows us to document new features in the future
- The structure is implemented reusing existing context where possible and creating new content where necessary

**Comment by akeller** [comment]
@meyerdan confirmed I can close this issue.
